### ISSUE TITLE
Update Markdown File

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#249]

**Comment by jpl-jengelke** [comment]
Hi ... PyPi had broken links so it requires fully-qualified domains that point to the images. Also, they have to be `/raw` links that point to the image itself. Because they were broken I made minor fixes. Also, I added proposed alternative text to help with PyPi. Please feel free to change anything.

**Comment by jpl-jengelke** [comment]
@pearsonkyle After the PR is pulled into `develop` please re-pull.

**Comment by pearsonkyle** [comment]
https://github.com/rzellem/EXOTIC/tree/issue249
