### ISSUE TITLE
Better installation instructions

### ISSUE THREAD

**Issue by pearsonkyle** [rzellem/EXOTIC#27]
Need an environment setup for windows people - issue with astroalign and compiling C code without setting up environment paths before hand
1. Native Windows
2. Anaconda

Better troubleshooting for common installation problems

**Comment by jpl-jengelke** [comment]
After helping one user get it working on a Windows box, here are some of my lessons: 
- [7zip](https://www.7-zip.org/) must be installed and its directory added to the path
- [Win-builds x64](https://wiki.python.org/moin/WindowsCompilers#GCC_-_MinGW-w64_.28x86.2C_x64.29) must be installed at **C:\\MinGW_w64** and its directory added to the path
- [Microsoft Visual Studio Community Edition (at least 2014)](https://wiki.python.org/moin/WindowsCompilers#Compilers_Installation_and_configuration) must be installed and on the path (which the installer should do automatically). **DURING INSTALLATION** the Linux tools should be selected and C++ tooling for the x64 or AMD platform. 
- If that doesn't bind things, install the latest [Microsoft Visual Studio Community edition](https://visualstudio.microsoft.com/vs/community/). **NOTE:** The older 2014 tooling should be installed before any installation of a newer Visual Studio Community Edition.
- A shortcut (aka symlink for Windows world) must point from **C:\\VC** to **C:\\Program Files(x86)\Microsoft Visual Studio 2014\VC**  (or a very similar path)
- Install [Python 3.7.7](https://www.python.org/downloads/release/python-377/) and *verify* it is pointing to the true version. It's recommended to uninstall old Python installations. Due to peculiarities with Windows security and installation conventions it potentially will point at a different Python file location embedded in hidden directories. It's critical to make sure that it point to the actual installation. Run `python --version` and `pip --version` to ensure they are correlated. Also, in **C:\\Users\\<user_name>\appdata\Local\pip** there is a cache of potentially munged old pip data with bad user perms. I would just delete it and replace installation items with the new `pip` install. This may need to be deleted *before* a reinstall. 
- `python -m pip install --upgrade pip` then `pip install setuptools` then `pip install -r requirements.txt`
- Stay away from `Anaconda`. Because Conda has its own package manager, installations are easily munged by running `pip` if it points to a different install or when pip does things differently from the `conda install` directive. 
- Recommended to install [Git-Bash CLI](https://git-scm.com/downloads) or [Sourcetree](https://www.sourcetreeapp.com/) for easy access to pulls, but it's not necessarily required if users download a release **ZIP** or **Tarball**.
- Instructions should be followed in order.

**Comment by jpl-jengelke** [comment]
NOTE: The above is rough and potentially Visual Studio may not need to be installed. More testing is required.

**Comment by jpl-jengelke** [comment]
Type `manage app execution aliases` at Windows Search and disable the following: 
![install_EXOTIC](https://user-images.githubusercontent.com/52300928/84834692-db9c1680-afe6-11ea-81b5-17e906ce4b5e.png)

**Comment by jpl-jengelke** [comment]
This is a suggested priority for Windows environment variable settings. The paths for Python, MinGW and 7-zip should be available and ordered. 
![install_EXOTIC2](https://user-images.githubusercontent.com/52300928/84837841-e4441b00-afed-11ea-96b1-a92d331a4ac9.png)

**Comment by jpl-jengelke** [comment]
This is the appearance of a properly launching `EXOTIC`: 
![install_EXOTIC3](https://user-images.githubusercontent.com/52300928/84838133-75b38d00-afee-11ea-8d5c-c776fbdc20b2.png)

**Comment by jpl-jengelke** [comment]
This is my current Desktop background (behind the above screenshots) if anyone is interested.
![SPACE-SHUTTLE-OVER-HOLLYWOOD](https://user-images.githubusercontent.com/52300928/85207009-af301500-b2da-11ea-80db-0a90d3ac4025.jpg)

**Comment by jpl-jengelke** [comment]
Here's some information about runtimoe compilation in Theano: http://deeplearning.net/software/theano/extending/pipeline.html#compilation-of-the-computation-graph

**Comment by jpl-jengelke** [comment]
**NOTE:** Windows users will also need to add an environment variable for `LDTK_ROOT` which points to `%USERPROFILE%\.ldtk`

**Comment by rzellem** [comment]
@mjs2369 - can you please add this additional step for Windows users that @jpl-jengelke recommended?

**Comment by pearsonkyle** [comment]
Closing for now. The documentation seems to be good
