### ISSUE TITLE
COMP_STAR-XC List Modification

### ISSUE THREAD

**Issue by tamimfatahi** [rzellem/EXOTIC#467]
Currently, EXOTIC leaves fields for COMP_STAR-XC as so: 
`#COMP_STAR-XC= {"ra": "205.91925353189598", "dec": "48.14073270140996", "x": "656", "y": "166"}`

Modify to: 
`#COMP_STAR-XC= [{"ra": "205.91925353189598", "dec": "48.14073270140996", "x": "656", "y": "166"}]`

Also, utilization of COMP_STAR-XC with no comparison star used is:
`#COMP_STAR-XC={"ra": null, "dec": null, "x": null, "y": null}`

Modify to:
~`#COMP_STAR-XC=[ ]`~
`#COMP_STAR-XC=[]`

This is to be more compatible with other reduction pipelines.

Edit: Typo. Accidentally left a space there.

**Comment by jpl-jengelke** [comment]
Please leave the empty version at [] (no spaces) since space may be used as a parsing delimiter. The less extraneous characters, the better.

Also, this should be releases ASAP to limit any submissions of bad data sets. We are going to have to add try-catch clauses to parse the JSON for each iteration where this changes.

Thanks

**Comment by rzellem** [comment]
^ @tamimfatahi

**Comment by tamimfatahi** [comment]
@jpl-jengelke My apologies. Typo in the issue. If you take a look at the PR, #469, there is no space there. Thanks!
