### ISSUE TITLE
UltraNest support

### ISSUE THREAD

**Issue by JohannesBuchner** [rzellem/EXOTIC#517]
Would you be interested to add support for https://johannesbuchner.github.io/UltraNest/ ?
The interface should be very similar to dynesty.
UltraNest is a very reliable tuning-parameter-free algorithm. It can be faster than dynesty, especially if you take advantage of vectorization.
It also supports resuming from disk and MPI parallelisation, if that is useful to you.

**Comment by pearsonkyle** [comment]
Hello! Thanks for bringing this to our attention, we're interested. I've used Multinest in the past with much success but didn't choose it for this because it was a little difficult to set up. If UltraNest is consistent with our current results and faster we'll likely adopt it. Might take a little while to test though

**Comment by tamimfatahi** [comment]
Completed in PR #831
