### ISSUE TITLE
Option to turn off image alignment

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#555]
Image alignment is still taking hours for @LeonBew - recommend we allow the user to turn off the image alignment and to use the centroid method to follow the drift of the star

Will need to figure out how to treat meridian flips - might be as easy as the code detecting a meridian flip (when the hour angle changes signs) or having the user define when that occurs and then have EXOTIC simply flip the images itself

**Comment by rzellem** [comment]
@LeonBew also recommends we look into:

Download: http://www.hnsky.org/astap.htm
Forum: https://sourceforge.net/p/astap-program/discussion/

hnsky.orghnsky.org
ASTAP, Astrometric Stacking Program
ASTAP, ASTrometric Stacking Program, astrometric solver, stacking of images, photometry and FITS viewer.

**Comment by LeonBew** [comment]
ASTAP provides high-speed platesolving which, if used in combination with EXOTIC, could significantly reduce both runtime and complexity of code needed for the initial alignment of the images. The workload would be reduced to shifting the solved images for the stars to be overlayed. 

Field of view and resolution would need to be taken from the .fits header (if available) or otherwise provided by the user. Providing these significantly really increases the already high speed of ASTAP in solving the images to near-instant solving. Problems _may_ arise however from elongated or non-circular stars. Nevertheless the integration of this software into the process is definitely worth considering for both alignment and platesolving (astrometric solving currently provided by astrometry.net).

**Comment by pearsonkyle** [comment]
The option has been added to the inits file. Defaults to performing alignment

https://github.com/rzellem/EXOTIC/pull/593
https://github.com/rzellem/EXOTIC/pull/606
