### ISSUE TITLE
Simplify Installation and Local Running

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#678]
Simplify EXOTIC's installation via Anaconda install and then 3 install scripts- 1 for each OS. The install will then make an icon that the user can click on to get a GUI that constructs the inits file and launches EXOTIC as a subprocess.

**Comment by jpl-jengelke** [comment]
I understand the impetus for this -- that Anaconda provides installers for different systems. However, ultimately, Anaconda is really just installing Python, but more aggressively. The problem is that once it's installed it overrides system Python. If users don't use `conda install ...` (instead favoring `pip install ...`) then the problems start. At some point, then, the Python subsystem is completely out of sync and the whole system needs work to pry it away from Anaconda. The `conda install ...` stuff is their package manager. It also favors approved packages (though a pass-through to unapproved packages) is available. This can complicate updates. For these reasons and others, please consider options that don't involve Anaconda. I will provide some examples shortly.

**Comment by jpl-jengelke** [comment]
Please look at [this guide on packaging](https://heartbeat.fritz.ai/packaging-and-shipping-python-apps-for-the-desktop-a418489b854). I would like to place particular emphasis on the image somewhat down the page. It packages the app as a regular system app.
