### ISSUE TITLE
Automatically constrain Tmid

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#949]
Important if the uncertainty on Tmid >= the length of the orbital period

**Comment by tamimfatahi** [comment]
Seems like this issue is solved (not sure in which PR, tagging @rzellem to verify):

`        
upper = pDict['midT'] + 35 * pDict['midTUnc'] + np.floor(phase).max() * (pDict['pPer'] + 35 * pDict['pPerUnc'])
lower = pDict['midT'] - 35 * pDict['midTUnc'] + np.floor(phase).max() * (pDict['pPer'] - 35 * pDict['pPerUnc'])

# clip bounds so they're within 1 orbit
if upper > prior['tmid'] + 0.5*prior['per']:
    upper = prior['tmid'] + 0.5*prior['per']
if lower < prior['tmid'] - 0.5*prior['per']:
    lower = prior['tmid'] - 0.5*prior['per']
`

**Comment by tamimfatahi** [comment]
Actually, we can add it within the `fit_lightcurve()` as well. Will open a PR and leave it up for review.

**Comment by tamimfatahi** [comment]
Completed in PR #1063
