### ISSUE TITLE
Tweak aperture sizes

### ISSUE THREAD

**Issue by rzellem** [rzellem/EXOTIC#968]
Start at 1FWHM per: 
https://uol-ets.slack.com/archives/CJJRP4QKV/p1646769488024799
https://ui.adsabs.harvard.edu/abs/1999ASPC..172..317M

**Comment by tamimfatahi** [comment]
The paper mentions starting at ~0.68 FWHM (~1.6 sigma). We test aperture sizes for 1.5 sigma to 6.0 sigma [here](https://github.com/rzellem/EXOTIC/blob/be96571b45cd08ab8e3de695ddc3d3bd2ad86c7e/exotic/exotic.py#L2071). I think we follow the paper (please read section 2.5), unless you say otherwise @rzellem. Will close this issue for now.
